### ISSUE TITLE
Create a modal for inputting todo items details

### ISSUE THREAD

**Issue by j-ngo828** [j-ngo828/TackleIt#1]
## Requirements

- [ ] Must have an input field for the following fields: `title`, `description`, `priority`.
- [x] Must be able to open it by clicking on a button saying "Add todo item"
- [x] Must be able to close it by clicking outside of the modal, or hitting Esc key

Will add `priority` later
