### ISSUE TITLE
Add validation for Todo item

### ISSUE THREAD

**Issue by j-ngo828** [j-ngo828/TackleIt#17]
## Requirements

- [x] Title is a required field
- [x] Description can be empty
- [x] isCompleted is a required field
- [x] Add form error state for frontend as needed
- Priority is fine as is I think, the default value is 'medium'

Ensure there are thorough automated testing in the backend
