### ISSUE TITLE
Create a todo items display component

### ISSUE THREAD

**Issue by j-ngo828** [j-ngo828/TackleIt#2]
## Requirements

- [ ] Must display all current todo items. With a pill at the start of the item to indicate the priority, then the item's title, then a button to check or uncheck to indicate completed or not
- [ ] The title text must be strikethrough once the item is completed. 
- [ ] Must be able to see the description beneath the todo item if user click on the title
