### ISSUE TITLE
Create skeleton UI for displaying todo items

### ISSUE THREAD

**Issue by j-ngo828** [j-ngo828/TackleIt#9]
## Requirements

- [ ] There's a header that displays "Tackle It" as the name
- [ ] There's a list of placeholder Todo Items
- [ ] There's a button for adding Todo Items
- [ ] There's a button for filtering completed and incomplete items

**Comment by j-ngo828** [comment]
Blocked by #6
